// dom()
const puzz = document.querySelector('#puzl')
const p1=document.createElement('p')
const msg= document.createElement('p')
p1.textContent=hangmanword.setword()
puzz.appendChild(p1)
window.addEventListener('keypress',function(e){
    msg.textContent=hangmanword.getpuzzel(e.key)
    p1.textContent=hangmanword.setword()
})
puzz.appendChild(msg)